[versions]

# Minecraft
fabricLoader = "0.18.3"
fabricKt = "1.13.7+kotlin.2.2.21"
loom = "1.14-SNAPSHOT"

# Dev Dependencies
devauth = "1.2.1"

[libraries]

fabricLoader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }
fabricKt = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabricKt" }

devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }